default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8
  timeout: 5000
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 0.0.0.0

development:
  adapter: mysql2
  encoding: utf8
  database: myapp_development
  pool: 5
  username: root
  password: password
  host: localhost
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  database: myapp_test
  pool: 5
  username: root
  password: password
  host: localhost
  port: 3306
production:
  adapter: mysql2
  encoding: utf8
  database: myapp_production
  pool: 5
  username: root
  password: password
  host: localhost
  port: 3306
